name: uptime-health (manual)
on:
  workflow_dispatch:
    inputs:
      url:
        description: "Health URL (ex: https://iot-vending-machine.osc-fr1.scalingo.io/health)"
        required: true
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call health endpoint
        id: call
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ github.event.inputs.url }}")
          echo "status=$STATUS" >> $GITHUB_OUTPUT
          echo "STATUS=$STATUS"
          if [ "$STATUS" != "200" ]; then exit 2; fi

      - name: Open issue on failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "ALERTE: Healthcheck KO (${{ steps.call.outputs.status }})"
          content-filepath: .github/health-alert-template.md
          labels: "bug,alert,supervision"

